Repository echo-webkom/echo-web, pull requests merged in 2022-12, with the labels that each got.

#613 🚑 Change to correct migration file name
  backend/src/main/resources/db/migration/V27__User_createdAt_modifiedAt.sql
Labels: fix :bug:

#614 ♻️ Replace Axios with native JavaScript fetch()
  backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
  frontend/package.json
  frontend/src/lib/api/banner.ts
  frontend/src/lib/api/dashboard.ts
  frontend/src/lib/api/feedback.ts
  frontend/src/lib/api/feide-group.ts
  frontend/src/lib/api/happening.ts
  frontend/src/lib/api/job-advert.ts
  frontend/src/lib/api/minute.ts
  frontend/src/lib/api/post.ts
  frontend/src/lib/api/profile.ts
  frontend/src/lib/api/reaction.ts
  frontend/src/lib/api/registration.ts
  frontend/src/lib/api/static-info.ts
  frontend/src/lib/api/student-group.ts
  frontend/src/lib/api/user.ts
  frontend/src/pages/api/registration/index.ts
  frontend/src/pages/arrangementer/index.tsx
  frontend/src/pages/index.tsx
  yarn.lock
Labels: refactor :recycle:

#617 🚑 Fix request breaking sign in
  frontend/src/lib/api/reaction.ts
  frontend/src/lib/api/user.ts
Labels: fix :bug:

#624 💚 Fix destroy backend action not working
  .github/workflows/destroy_backend_preview.yaml
Labels: ci :rocket:

#635 ✨ Student group filter on registrations list
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
  frontend/src/pages/event/[slug].tsx
Labels: feat :sparkles:

#646 ✨ Add rate limiting for backend
  backend/build.gradle.kts
  backend/src/main/kotlin/no/uib/echo/Application.kt
  backend/src/main/kotlin/no/uib/echo/plugins/RateLimit.kt
  backend/src/test/kotlin/no/uib/echo/status/GetStatusTest.kt
  terraform/dev/main.tf
Labels: feat :sparkles:

#650 🐛 Fix multiple routes using fixed JWT config
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
  backend/src/main/kotlin/no/uib/echo/routes/FeedbackRoutes.kt
  backend/src/main/kotlin/no/uib/echo/routes/ReactionRoutes.kt
  backend/src/main/kotlin/no/uib/echo/routes/StudentGroupRoutes.kt
Labels: fix :bug:

#648 🗃 Handle database initialization and migration better
  backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
  terraform/dev/main.tf
  terraform/preview/main.tf
Labels: ci :rocket:

#653 🐛 Fix earlier PR breaking local backend
  backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
Labels: fix :bug:

#667 🔥 Remove rebase action
  .github/workflows/rebase.yaml
Labels: ci :rocket:

#688 ✨ Student group statistics
  frontend/src/components/registration-pie-chart.tsx
  frontend/src/components/registrations-list.tsx
Labels: feat :sparkles:

#704 🐛 Add missing Sanity CLI config for deployment
  cms/sanity.cli.ts
Labels: fix :bug:

#707 🧑‍💻 Hide dev workspaces from bedkom
  cms/env.d.ts
  cms/sanity.config.ts
Labels: build :handshake:

#713 🔒️ Update security.txt
  frontend/next.config.js
  frontend/public/security.txt
Labels: chore :muscle:
