Repository echo-webkom/echo-web, pull requests merged in 2022-10, with the labels that each got.

#380 🐛 Fix wrong month & JSX order of animated icons
  frontend/src/components/animated-icons.tsx
  frontend/src/components/layout.tsx
Labels: fix :bug:

#383 💄 Add degree on registrations list
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
Labels: style :lipstick:

#386 💄Added timestamp on front page
  frontend/src/components/happening-key-info.tsx
  frontend/src/components/happening-meta-info.tsx
Labels: style :lipstick:

#388 🙈 Add bin/ to gitignore
  backend/.gitignore
Labels: chore :muscle:

#395 Style/jaj for faj
  frontend/src/components/header-logo.tsx
Labels: style :lipstick:

#393 💄 Polished timestamp
  frontend/src/components/happening-key-info.tsx
Labels: fix :bug:, style :lipstick:

#404 Revert "🔧 Increase JWT expire to 1 week"
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: revert :rewind:

#394 Replace profile icon with text
  frontend/src/components/nav-link.tsx
  frontend/src/components/navbar.tsx
Labels: style :lipstick:

#421 Add .vercel to gitignore
  .gitignore
Labels: ci 🚀

#428 Remove isMainPage boolean in happening-key-info
  frontend/src/components/happening-key-info.tsx
Labels: fix :bug:, feat :sparkles:

#429 Fix backend url arrangementer page
  frontend/src/pages/arrangementer/index.tsx
Labels: fix :bug:

#432 🐛 Fix placeholder name in profile page
  frontend/src/components/profile-info.tsx
  frontend/src/pages/api/user/index.ts
Labels: fix :bug:

#435 🚸 Improve user experience of feedback page
  frontend/src/pages/tilbakemeldinger/index.tsx
Labels: style :lipstick:

#437 💄 Update style of reglist and stats
  frontend/src/components/registration-pie-chart.tsx
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
Labels: style :lipstick:

#438 ⏪️ Fix bad commit to reglist
  frontend/src/components/registrations-list.tsx
Labels: revert :rewind:

#444 Increase session lifetime to 8 hours
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: fix :bug:, feat :sparkles:

#448 💬 Add .txt file for Microsoft Non-profit program
  frontend/public/ms17036040.txt
Labels: chore :muscle:

#454 🔥 Remove unused scripts
  backend/scripts/delete_happening
  backend/scripts/delete_registration
  backend/scripts/get_count_registrations
  backend/scripts/submit_happening
  backend/scripts/submit_registration
  backend/scripts/test
Labels: refactor :recycle:

#457 ✨ Sort registrations
  frontend/src/components/registrations-list.tsx
Labels: feat :sparkles:

#458 ✨ Add search to reglist
  frontend/src/components/registrations-list.tsx
Labels: feat :sparkles:

#459 ♻️ Add button to clear search
  frontend/src/components/registrations-list.tsx
Labels: refactor :recycle:

#460 🐛 Fix black modal & deleting wrong feedback
  frontend/src/components/feedback-entry.tsx
  frontend/src/pages/tilbakemeldinger/index.tsx
Labels: fix :bug:

#468 🐛 Close client
  backend/src/main/kotlin/no/uib/echo/SanityClient.kt
Labels: fix :bug:

#477 tilbakeknapp for dashboard
  frontend/src/pages/dashboard/brukere.tsx
  frontend/src/pages/dashboard/tilbakemeldinger.tsx
Labels: feat :sparkles:

#496 🐛 Remove `.` and `renovate/` from branch name to Azure
  .github/workflows/docker_tests_and_previews.yaml
Labels: ci :rocket:
