Repository echo-webkom/echo-web, pull requests merged in 2022-11, with the labels that each got.

#506 🍱 Add Hyggkom
  frontend/src/components/sidebar.tsx
Labels: feat :sparkles:

#525 Limit custom theme real estate
  frontend/src/styles/theme.ts
Labels: fix :bug:, feat :sparkles:, refactor :recycle:

#526 Add esc
  frontend/src/components/sidebar.tsx
Labels: feat :sparkles:

#534 🐛 Add missing prefix to environment variable
  frontend/src/lib/api/dashboard.ts
Labels: fix :bug:

#539 Add highlighted reactions
  backend/src/main/kotlin/no/uib/echo/routes/ReactionRoutes.kt
  backend/src/main/kotlin/no/uib/echo/schema/Reaction.kt
  frontend/src/components/reaction-buttons.tsx
  frontend/src/lib/api/reaction.ts
Labels: style :lipstick:

#540 🐛 Fix reactions not showing
  backend/src/main/kotlin/no/uib/echo/routes/ReactionRoutes.kt
  backend/src/main/kotlin/no/uib/echo/schema/Reaction.kt
  frontend/src/components/reaction-buttons.tsx
  frontend/src/lib/api/reaction.ts
  frontend/src/pages/event/[slug].tsx
Labels: fix :bug:

#571 🔥 Remove pwc header message
  frontend/src/components/header-logo.tsx
Labels: refactor :recycle:

#575 🐛 Filter non Feide users on dashboard
  backend/src/main/kotlin/no/uib/echo/routes/UserRoutes.kt
  frontend/src/pages/profile.tsx
Labels: fix :bug:

#578 🐛 Fix registration count on /event/[slug]
  backend/src/main/kotlin/no/uib/echo/schema/Registration.kt
Labels: fix :bug:

#585 ✨ Som arrangør vil jeg ha oversikt over hvilken undergruppe de påmeld…
  backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
  backend/src/main/kotlin/no/uib/echo/schema/Registration.kt
  backend/src/test/kotlin/no/uib/echo/CommonData.kt
  backend/src/test/kotlin/no/uib/echo/registration/GetRegistrationsTest.kt
  frontend/package.json
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
  frontend/src/lib/api/registration.ts
Labels: feat :sparkles:

#592 🐛 Fix wrong operator
  backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
Labels: fix :bug:

#598 💚 Feide tests works???
  .github/workflows/docker_tests_and_previews.yaml
  frontend/cypress.config.ts
  frontend/cypress/e2e/feide-sign-in.spec.ts
  frontend/cypress/e2e/happening-registration.spec.ts
  frontend/cypress/support/e2e.ts
  frontend/src/components/profile-info.tsx
Labels: ci :rocket:

#602 Combine countdown and reg button
  frontend/src/components/countdown-button.tsx
  frontend/src/components/countdown.tsx
  frontend/src/components/registration-form.tsx
Labels: fix :bug:, refactor :recycle:, perf :zap:

#604 🐛 Fix error handling when no `idToken`
  frontend/src/pages/dashboard/brukere.tsx
  frontend/src/pages/dashboard/tilbakemeldinger.tsx
Labels: fix :bug:

#605 ♻️ Change to correct text on /nei & simplify logic
  frontend/src/pages/api/auth/[...nextauth].ts
  frontend/src/pages/nei.tsx
Labels: refactor :recycle:
