Repository echo-webkom/echo-web, pull requests merged in 2022-09, with the labels that each got.

#273 🐛 Fix wrong literal for degree decoder
  frontend/src/lib/utils/decoders.ts
Labels: fix :bug:

#274 Add .vscode to gitignore
  .gitignore
Labels: chore :muscle:

#275 Fixed unique slug generation
  cms/sanity.json
  cms/schemas/Happening.js
  cms/src/resolveDocumentActions.js
  cms/src/setAndPublishAction.js
Labels: fix :bug:

#290 🐛 Sort feedback by date
  frontend/src/lib/api/feedback.ts
  frontend/src/pages/tilbakemeldinger/index.tsx
Labels: fix :bug:, style :lipstick:

#292 🐛 Properly fix slugs for all schemas using it
  cms/package.json
  cms/schemas/Happening.js
  cms/schemas/Post.js
  cms/schemas/StudentGroup.js
  yarn.lock
Labels: fix :bug:

#297 🐛 Remove spicy characters from slug
  cms/schemas/Happening.js
  cms/schemas/Post.js
  cms/schemas/StudentGroup.js
Labels: fix :bug:

#309 🐛 Strip special chars from slugs
  cms/schemas/Happening.js
  cms/schemas/Post.js
  cms/schemas/StudentGroup.js
Labels: fix :bug:

#320 translated the profile page
  frontend/src/components/form-degree-year.tsx
  frontend/src/components/form-degree.tsx
  frontend/src/components/profile-info.tsx
  frontend/src/pages/profile.tsx
Labels: style :lipstick:

#335 🐛 Add case for when user is not in a student group
  frontend/src/components/profile-info.tsx
Labels: fix :bug:

#338 💄 Fix overflow of regs list & table heading
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
  frontend/src/lib/utils/not-empty-or-null.ts
  frontend/src/pages/event/[slug].tsx
Labels: style :lipstick:

#350 ✨ Add support for Sanity auto-cropping images
  cms/schemas/JobAdvert.js
  frontend/package.json
  frontend/src/lib/api/sanity.ts
  frontend/src/pages/jobb/[slug].tsx
  yarn.lock
Labels: feat :sparkles:

#351 💬 Update text & translations for job adverts
  frontend/src/components/job-advert-preview.tsx
  frontend/src/lib/utils/degree-year-text.ts
  frontend/src/lib/utils/translate-job-type.ts
  frontend/src/pages/jobb/[slug].tsx
Labels: style :lipstick:

#356 Scale in sanity profiles
  cms/schemas/Profile.js
Labels: feat :sparkles:

#358 Credits page
  frontend/package.json
  frontend/src/components/member-profile.tsx
  frontend/src/lib/api/profile.ts
  frontend/src/lib/api/student-group.ts
  frontend/src/pages/credits.tsx
  yarn.lock
Labels: feat :sparkles:

#367 🔧 Remove ktlint commit hook
  .husky/pre-commit
Labels: ci 🚀

#371 🔧 Increase JWT expire to 1 week
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: fix :bug:
