Repository echo-webkom/echo-web, pull requests merged in 2022-08, with the labels that each got.

#208 ✅ Temp disable registration deletion test
  frontend/cypress.config.ts
Labels: testing :test_tube:

#217 🔥 Remove old feedback link
  frontend/src/components/footer.tsx
Labels: refactoring :recycle:

#231 ✨ Add welcome message
  frontend/src/components/header-logo.tsx
Labels: feature :sparkles:

#232 ✨ Alternate email in profile info
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
  backend/src/main/kotlin/no/uib/echo/schema/User.kt
  backend/src/main/resources/db/migration/V17__Alternate_email_user.sql
  frontend/src/components/profile-info.tsx
  frontend/src/components/registration-form.tsx
  frontend/src/lib/api/decoders.ts
  frontend/src/lib/api/user.ts
  frontend/src/pages/api/auth/[...nextauth].ts
  frontend/src/pages/api/user/index.ts
Labels: feature :sparkles:

#236 🐛 Account for people on waitlist in key info
  frontend/src/components/happening-key-info.tsx
Labels: bug :bug:

#238 🐛 Fix old events not showing registrations
  frontend/src/lib/api/decoders.ts
Labels: bug :bug:

#242 🐛 Fix names able to be empty strings
  backend/src/main/kotlin/no/uib/echo/Response.kt
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
  frontend/src/components/registration-form.tsx
Labels: bug :bug:

#244 🔧 Change Renovate label to match new label name
  .github/renovate.json
Labels: ci 🚀

#243 🔥 Remove 'Annet studieløp' as degree option
  backend/src/main/kotlin/no/uib/echo/schema/Degree.kt
  frontend/src/components/form-degree.tsx
  frontend/src/lib/api/types.ts
Labels: refactor :recycle:

#252 💚 Include 'fetch-depth' for Docker build on push
  .github/workflows/docker_push.yaml
Labels: ci 🚀

#253 🐛 Check edge case where spotRanges can be empty array
  cms/schemas/Happening.js
Labels: fix :bug:

#263 💄 Move log out button
  frontend/src/components/profile-info.tsx
  frontend/src/pages/profile.tsx
Labels: style :lipstick:

#265 🐛 Fix typo in BACKEND_URL
  frontend/src/pages/tilbakemeldinger/index.tsx
Labels: fix :bug:

#266 I can't log in this is fix pls merge
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
Labels: fix :bug:

#268 Fix user get wrong case email
  backend/src/main/kotlin/no/uib/echo/plugins/Routing.kt
Labels: fix :bug:

#269 🤡 Add webkommers
  frontend/src/lib/api/feedback.ts
Labels: chore :muscle:

#270 ✏️ Add header messages
  frontend/src/components/header-logo.tsx
Labels: chore :muscle:
