Repository echo-webkom/echo-web, pull requests merged in 2023-01, with the labels that each got.

#714 💚 Properly get ref name in restart container action
  .github/workflows/restart_backend_preview.yaml
Labels: ci :rocket:

#741 🐛 Fix Renovate config & docker push action
  .github/renovate.json
  .github/workflows/docker_push_deploy.yaml
Labels: fix :bug:

#752 ✨ Add echo Brettspill 🎲
  frontend/src/components/sidebar.tsx
Labels: feat :sparkles:

#770 🔥 Remove Heroku-specific configs & code
  .github/workflows/deploy.yaml
  .github/workflows/docker_tests_and_previews.yaml
  .github/workflows/heroku_deploy.yaml
  backend/Dockerfile
  backend/Procfile
  backend/build.gradle.kts
  backend/docker-compose.kotest.yaml
  backend/src/main/resources/db/Dockerfile
  backend/system.properties
Labels: ci :rocket:

#774 🔧 Make Renovate pin devDeps & group azurerm updates
  .github/renovate.json
Labels: ci :rocket:

#782 💄 Add @next/font
  frontend/package.json
  frontend/src/components/countdown-button.tsx
  frontend/src/pages/_app.tsx
  frontend/src/styles/fonts.tsx
  frontend/src/styles/themes/main-theme.ts
  yarn.lock
Labels: refactor :recycle:

#783 🚨 Fix wrong linter warnings for date-fns imports
  .gitignore
  frontend/package.json
  frontend/src/components/calendar-popup.tsx
  frontend/src/components/happening-key-info.tsx
  frontend/src/components/header-logo.tsx
  frontend/src/components/minute-list.tsx
  frontend/src/components/registration-form.tsx
  frontend/src/pages/event/[slug].tsx
  frontend/src/pages/jobb/[slug].tsx
  frontend/src/pages/posts/[slug].tsx
  package.json
  yarn.lock
Labels: fix :bug:

#784 ♻️ Toast to modal
  frontend/src/components/registrations-list.tsx
Labels: refactor :recycle:

#786 ⚡️ Improve load times for /event/[slug] w/ caching
  frontend/src/pages/event/[slug].tsx
Labels: perf :zap:

#787 ⚡️ Massively reduce /event/[slug] bundle size
  frontend/src/components/registrations-list.tsx
  frontend/src/pages/event/[slug].tsx
Labels: perf :zap:

#788 ♻️ Remove redundant layout and padding
  frontend/src/components/button-link.tsx
  frontend/src/components/entry-box.tsx
  frontend/src/components/header-logo.tsx
  frontend/src/components/header.tsx
  frontend/src/components/navbar.tsx
Labels: refactor :recycle:

#789 🥅 Don't show error on getRegistrations status 404
  frontend/src/lib/api/registration.ts
Labels: fix :bug:

#793 🥅 Actually don't show error on getRegistrations status 404
  frontend/src/lib/api/registration.ts
Labels: fix :bug:

#792 ♻️ Various refactoring
  frontend/src/components/article.tsx
  frontend/src/components/happening-meta-info.tsx
  frontend/src/components/layout.tsx
  frontend/src/components/reaction-buttons.tsx
  frontend/src/pages/event/[slug].tsx
Labels: refactor :recycle:

#799 🐛 Fix bad image scaling
  frontend/src/components/bedpres-preview.tsx
Labels: fix :bug:

#801 🚑 Fix wrong reference to env var in deploy action
  .github/workflows/deploy.yaml
Labels: fix :bug:, ci :rocket:

#798 ✨ Vercel OG image
  frontend/next.config.js
  frontend/package.json
  frontend/src/assets/BebasNeue-Regular.ttf
  frontend/src/assets/small-echo-logo.png
  frontend/src/pages/api/og/bedpres.tsx
  frontend/src/pages/event/[slug].tsx
  yarn.lock
Labels: feat :sparkles:

#809 ♻️ Refactor /api/auth route, remove unnecessary API call & change syntax
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: refactor :recycle:

#816 🔇 Clean up output from backend logs
  backend/src/main/resources/logback.xml
Labels: refactor :recycle:

#821 ✨ Sort users by modifiedAt & shrink table size
  frontend/src/pages/dashboard/brukere.tsx
Labels: feat :sparkles:, style :lipstick:

#824 ✨ Add whitelist for users
  backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
  backend/src/main/kotlin/no/uib/echo/routes/UserRoutes.kt
  backend/src/main/kotlin/no/uib/echo/schema/Whitelist.kt
  backend/src/main/resources/db/migration/V28__Whitelist.sql
  frontend/src/lib/api/user.ts
  frontend/src/pages/api/auth/[...nextauth].ts
  frontend/src/pages/dashboard/index.tsx
  frontend/src/pages/dashboard/whitelist.tsx
Labels: feat :sparkles:

#837 💄 Reduce number of happenings on front page
  frontend/src/pages/index.tsx
Labels: style :lipstick:

#830 🚑️ Fix default sanity spotRange parse error
  frontend/src/lib/api/happening.ts
Labels: fix :bug:
