Repository echo-webkom/echo-web, pull requests merged in 2023-02, with the labels that each got.

#845 Fix readonly for happening regdate
  cms/schemas/happening.ts
Labels: fix :bug:

#859 💄 Improve job page heading
  frontend/src/components/job-advert-overview.tsx
  frontend/src/pages/jobb/index.tsx
Labels: refactor :recycle:, style :lipstick:

#866 Fix registrationDate validation error on spotrange
  cms/schemas/happening.ts
Labels: fix :bug:

#872 🚸 Show spinner when waiting for registration
  frontend/src/components/registration-form.tsx
Labels: feat :sparkles:

#874 🐛 Add hyggkom
  frontend/src/lib/api/dashboard.ts
  frontend/src/lib/api/happening.ts
Labels: fix :bug:

#875 🔥 Remove reaction count on events
  frontend/src/components/bedpres-preview.tsx
  frontend/src/components/event-preview.tsx
  frontend/src/components/happening-preview.tsx
  frontend/src/components/reaction-count.tsx
Labels: revert :rewind:

#871 ✨ Skip degreeYear-check for registration if Bedkom
  backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
  backend/src/test/kotlin/no/uib/echo/registration/PostRegistrationsTest.kt
Labels: feat :sparkles:

#844 ny feature alert_echo om du opplever noe ugreit🚫
  frontend/src/components/footer.tsx
  frontend/src/components/sidebar.tsx
Labels: feat :sparkles:

#881 🐛 Fix misleading text when happening has student group registration
  frontend/src/components/happening-key-info.tsx
  frontend/src/lib/utils/parse-iso-or-null.ts
Labels: fix :bug:

#882 ✏️ Add programmerbar
  backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
  backend/src/main/kotlin/no/uib/echo/schema/StudentGroup.kt
  backend/src/main/resources/db/migration/V29__Programmerbar.sql
  cms/schemas/happening.ts
  frontend/src/lib/api/dashboard.ts
Labels: fix :bug:

#888 ✨ Add random person picker to registrations list
  frontend/src/components/registrations-list.tsx
Labels: feat :sparkles:

#897 🐛 Fix wrong count on /event/[slug]
  backend/src/main/kotlin/no/uib/echo/routes/HappeningRoutes.kt
Labels: fix :bug:

#901 🐛 Fix onlyForStudentGroups not triggering update
  backend/src/main/kotlin/no/uib/echo/schema/Happening.kt
Labels: fix :bug:

#903 🚀 Fix Terraform not deploying when TF & backend files change
  .github/workflows/deploy.yaml
Labels: ci :rocket:

#906 Fix NaN in spotrange validation
  cms/schemas/spotRange.ts
Labels: fix :bug:

#913 ♻️ Refactor email sending & fix confirmation email
  backend/src/main/kotlin/no/uib/echo/Email.kt
  backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
  backend/src/main/kotlin/no/uib/echo/schema/Registration.kt
  backend/src/main/kotlin/no/uib/echo/schema/WaitinglistUUID.kt
  frontend/src/pages/WaitingList/[uuid].tsx
Labels: refactor :recycle:

#931 🚸 Hide job adverts with deadline in the past
  frontend/src/pages/index.tsx
Labels: feat :sparkles:

#934 🐛 Fix wrong reg date
  frontend/src/components/happening-key-info.tsx
  frontend/src/components/registration-form.tsx
  frontend/src/lib/utils/choose-date.ts
Labels: fix :bug:

#935 🐛 Don't show registrations chart when there are none
  frontend/src/components/registrations-list.tsx
Labels: fix :bug:

#936 ✏️ Fix wrong reg date again
  frontend/src/components/happening-key-info.tsx
Labels: fix :bug:

#937 🐛 Invalid dom
  frontend/src/components/happening-calendar-box.tsx
Labels: fix :bug:

#938 ⚡️ Drastically reduce amount of happenings in queries from /index
  frontend/src/lib/api/happening.ts
  frontend/src/pages/index.tsx
Labels: perf :zap:

#939 🏗 Increase backend rate limit
  backend/src/main/kotlin/no/uib/echo/plugins/RateLimit.kt
  backend/src/test/kotlin/no/uib/echo/status/GetStatusTest.kt
Labels: fix :bug:

#942 🏗️ Replace Container Instances with Container Apps
  .github/workflows/deploy.yaml
  .github/workflows/terraform_format_plan.yaml
  terraform/main/.terraform.lock.hcl
  terraform/main/dev/main.tf
  terraform/main/dev/outputs.tf
  terraform/main/dev/variables.tf
  terraform/main/main.tf
  terraform/main/modules/container_app/main.tf
  terraform/main/modules/container_app/outputs.tf
  terraform/main/modules/container_app/variables.tf
  terraform/main/prod/main.tf
  terraform/main/prod/outputs.tf
  terraform/main/prod/variables.tf
  terraform/main/variables.tf
Labels: ci :rocket:
