Repository echo-webkom/echo-web, pull requests merged in 2023-10, with the labels that each got.

#1552 🎶 Add informatikkband
  frontend/src/components/sidebar.tsx
Labels: chore :muscle:

#1560 💄 Make job advert tags use Halloween theme colors
  frontend/src/components/job-advert-preview.tsx
  frontend/src/styles/themes/halloween-theme.ts
Labels: style :lipstick:

#1569 ✨ Add brochure
  frontend/src/pages/brosjyre.tsx
Labels: feat :sparkles:

#1582 ♻️ Move brochure
  frontend/src/components/sidebar.tsx
  frontend/src/pages/brosjyre.tsx
  frontend/src/pages/om-echo/brosjyre.tsx
Labels: refactor :recycle:

#1590 ♻️ Refactor sidebar routes
  frontend/src/components/sidebar.tsx
  frontend/src/lib/routes.ts
Labels: refactor :recycle:

#1592 👷 Node 16 -> 18
  .github/workflows/build_cms.yaml
  .github/workflows/cypress_component_tests.yaml
  .github/workflows/lint_format.yaml
  .github/workflows/sanity_deploy.yaml
Labels: ci :rocket:

#1622 ✨ Show number on registration
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
Labels: feat :sparkles:

#1630 Revert "⬆️ Update nextjs monorepo to v14 (major)"
  frontend/package.json
  yarn.lock
Labels: revert :rewind:
