Repository echo-webkom/echo-web, pull requests merged in 2023-03, with the labels that each got.

#956 🔥 Remove echo karriere
  frontend/src/components/sidebar.tsx
Labels: fix :bug:

#958 🐛 Fix answer sometimes showing up on wrong question
  backend/src/main/kotlin/no/uib/echo/routes/RegistrationRoutes.kt
  backend/src/main/kotlin/no/uib/echo/schema/Answer.kt
Labels: fix :bug:

#967 🚀 Change Vercel deploy action to a better one
  .github/workflows/docker_tests_and_previews.yaml
Labels: ci :rocket:

#977 Add link on popovertrigger
  frontend/src/components/happening-calendar-box.tsx
Labels: feat :sparkles:, chore :muscle:

#969 ♻️ Bedpres image instead of title on smaller screens
  frontend/src/components/bedpres-preview.tsx
Labels: refactor :recycle:

#959 🚸 Fix UX issues on registrations list
  frontend/src/components/promote-button.tsx
  frontend/src/components/registration-row.tsx
  frontend/src/components/registrations-list.tsx
Labels: style :lipstick:

#978 Spotrange migration
  backend/src/main/kotlin/no/uib/echo/routes/SanityRoutes.kt
  cms/schemas/happening.ts
  cms/schemas/index.ts
  cms/schemas/spotRange.ts
  cms/scripts/migrate-spotrange.js
  frontend/src/lib/api/happening.ts
Labels: chore :muscle:, refactor :recycle:

#992 🚑 Add missing migration for user strikes
  backend/src/main/kotlin/no/uib/echo/DatabaseHandler.kt
  backend/src/main/resources/db/migration/V31__Strikes.sql
Labels: fix :bug:

#993 Add warning message if backend is down
  frontend/package.json
  frontend/public/tradeoffer.ogg
  frontend/src/components/layout.tsx
  yarn.lock
Labels: feat :sparkles:

#994 🐛 Fix dashboard access
  backend/src/main/kotlin/no/uib/echo/routes/UserRoutes.kt
  frontend/src/components/profile-info.tsx
  frontend/src/pages/dashboard/index.tsx
Labels: fix :bug:

#1011 💄 Increase bedpres count
  frontend/src/pages/index.tsx
Labels: style :lipstick:

#1016 🐛 Hide job adverts on /jobb when deadline has expired
  frontend/src/lib/api/job-advert.ts
Labels: fix :bug:

#1018 ✏️ Add hovedstyret 2023-2024
  frontend/src/components/sidebar.tsx
Labels: chore :muscle:

#1017 🐛 Fix OG image overflow on long bedpres titles
  frontend/src/pages/api/og/bedpres.tsx
Labels: fix :bug:

#1021 🐛 Remove last line export on OG image
  frontend/src/pages/api/og/bedpres.tsx
Labels: fix :bug:

#1053 fixed slug fail on innlegg
  cms/schemas/post.ts
Labels: fix :bug:

#1069 Revert "💄 Increase bedpres count"
  frontend/src/pages/index.tsx
Labels: revert :rewind:
